name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # ou a branch que você usa para produção

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # ou a versão que você está usando

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # se você tiver um comando de build

      - name: Deploy to Firebase
        run: npm run deploy  # se você tiver um script de deploy no seu package.json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DIDIIRED_7E6ED }}  # usa seu token
